imu0:
  T_i_b:
  - [1.0, 0.0, 0.0, 0.0]
  - [0.0, 1.0, 0.0, 0.0]
  - [0.0, 0.0, 1.0, 0.0]
  - [0.0, 0.0, 0.0, 1.0]
  accelerometer_noise_density: 0.02
  accelerometer_random_walk: 0.003
  gyroscope_noise_density: 0.0016968
  gyroscope_random_walk: 1.9393e-05
  model: calibrated
  rostopic: /camera/imu
  time_offset: 0.0
  update_rate: 200.0
